export const stocksList = [
  { symbol: 'AAPL', name: 'Apple Inc.' },
  { symbol: 'MSFT', name: 'Microsoft Corporation' },
  { symbol: 'GOOGL', name: 'Alphabet Inc.' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.' },
  { symbol: 'TSLA', name: 'Tesla Inc.' },
  { symbol: 'META', name: 'Meta Platforms Inc.' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.' },
  { symbol: 'V', name: 'Visa Inc.' },
  { symbol: 'JNJ', name: 'Johnson & Johnson' },
  { symbol: 'WMT', name: 'Walmart Inc.' },
  { symbol: 'DIS', name: 'The Walt Disney Company' },
  { symbol: 'NFLX', name: 'Netflix Inc.' },
  { symbol: 'PYPL', name: 'PayPal Holdings Inc.' },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.' },
  { symbol: 'INTC', name: 'Intel Corporation' },
  { symbol: 'AMD', name: 'Advanced Micro Devices Inc.' },
  { symbol: 'QCOM', name: 'Qualcomm Inc.' },
  { symbol: 'IBM', name: 'International Business Machines' },
  { symbol: 'ORCL', name: 'Oracle Corporation' },
  { symbol: 'SAP', name: 'SAP SE' },
  { symbol: 'CRM', name: 'Salesforce Inc.' },
  { symbol: 'NOW', name: 'ServiceNow Inc.' },
  { symbol: 'AZN', name: 'AstraZeneca PLC' },
  { symbol: 'PFE', name: 'Pfizer Inc.' },
  { symbol: 'MRK', name: 'Merck & Co. Inc.' },
  { symbol: 'ABT', name: 'Abbott Laboratories' },
  { symbol: 'LLY', name: 'Eli Lilly and Company' },
  { symbol: 'UNH', name: 'UnitedHealth Group Inc.' },
  { symbol: 'CVS', name: 'CVS Health Corporation' },
  { symbol: 'XOM', name: 'Exxon Mobil Corporation' },
  { symbol: 'COP', name: 'ConocoPhillips' },
  { symbol: 'MPC', name: 'Marathon Petroleum Corporation' },
  { symbol: 'PSX', name: 'Phillips 66' },
  { symbol: 'VLO', name: 'Valero Energy Corporation' },
  { symbol: 'BAC', name: 'Bank of America Corporation' },
  { symbol: 'WFC', name: 'Wells Fargo & Company' },
  { symbol: 'GS', name: 'The Goldman Sachs Group Inc.' },
  { symbol: 'MS', name: 'Morgan Stanley' },
  { symbol: 'BLK', name: 'BlackRock Inc.' },
  { symbol: 'COF', name: 'Capital One Financial Corporation' },
  { symbol: 'AXP', name: 'American Express Company' },
  { symbol: 'MA', name: 'Mastercard Incorporated' },
  { symbol: 'BA', name: 'The Boeing Company' },
  { symbol: 'CAT', name: 'Caterpillar Inc.' },
  { symbol: 'MMM', name: '3M Company' },
  { symbol: 'HON', name: 'Honeywell International Inc.' },
  { symbol: 'GE', name: 'General Electric Company' },
  { symbol: 'RTX', name: 'Raytheon Technologies Corporation' },
  { symbol: 'LMT', name: 'Lockheed Martin Corporation' },
  { symbol: 'F', name: 'Ford Motor Company' },
  { symbol: 'GM', name: 'General Motors Company' },
  { symbol: 'TM', name: 'Toyota Motor Corporation' },
  { symbol: 'HMC', name: 'Honda Motor Co. Inc.' },
  { symbol: 'UBER', name: 'Uber Technologies Inc.' },
  { symbol: 'LYFT', name: 'Lyft Inc.' },
  { symbol: 'PG', name: 'The Procter & Gamble Company' },
  { symbol: 'KO', name: 'The Coca-Cola Company' },
  { symbol: 'PEP', name: 'PepsiCo Inc.' },
  { symbol: 'MCD', name: "McDonald's Corporation" },
  { symbol: 'SBUX', name: 'Starbucks Corporation' },
  { symbol: 'NKE', name: 'Nike Inc.' },
  { symbol: 'ADIDAS', name: 'Adidas AG' },
  { symbol: 'LULU', name: 'Lululemon Athletica Inc.' },
  { symbol: 'TJX', name: 'The TJX Companies Inc.' },
  { symbol: 'HD', name: 'The Home Depot Inc.' },
  { symbol: 'LOW', name: "Lowe's Companies Inc." },
  { symbol: 'TARGET', name: 'Target Corporation' },
  { symbol: 'COST', name: 'Costco Wholesale Corporation' },
  { symbol: 'SO', name: 'Southern Company' },
  { symbol: 'NEE', name: 'NextEra Energy Inc.' },
  { symbol: 'DUK', name: 'Duke Energy Corporation' },
  { symbol: 'EXC', name: 'Exelon Corporation' },
  { symbol: 'PCG', name: 'PG&E Corporation' },
  { symbol: 'AEP', name: 'American Electric Power Company Inc.' },
  { symbol: 'KMI', name: 'Kinder Morgan Inc.' },
  { symbol: 'OKE', name: 'ONEOK Inc.' },
  { symbol: 'PSA', name: 'Public Storage' },
  { symbol: 'PLD', name: 'Prologis Inc.' },
  { symbol: 'EQIX', name: 'Equinix Inc.' },
  { symbol: 'DLR', name: 'Digital Realty Trust Inc.' },
  { symbol: 'VICI', name: 'VICI Properties Inc.' },
  { symbol: 'WELL', name: 'Welltower Inc.' },
  { symbol: 'O', name: 'Realty Income Corporation' },
  { symbol: 'PFF', name: 'iShares Preferred Stock ETF' },
  { symbol: 'GLD', name: 'SPDR Gold Shares' },
  { symbol: 'SLV', name: 'iShares Silver Trust' },
];
